app:
    dataDirectory: acey

server:
    binding: 0.0.0.0:8100
    accessToken: ~
    logRequests: Y

aceApi:
    endpoint: http://127.0.0.1:6878
    requestTimeout: 1m

ttvApi:
    username: username
    password: password
    endpoint: http://api.torrent-tv.ru
    requestTimeout: 20s

stream:
    stopDelay: 3s
    responseTimeout: 2m
    sharedBufferLength: 20s

ffmpeg:
    binPath: ~
    outPath: ~
    logOutput: Y

hls:
    v3:
        idleTimeout: 10s
        segmentLength: 2s
        minListLength: 8s
        maxListLength: 12s
        minInitListLength: 3s
        minPrebufferLength: 4s
        deleteThresholdLength: 4s
        ffmpegArgs: >
            -f mpegts
            -i pipe:0
            -c copy
            -hls_time {hlsTime}
            -hls_list_size {hlsListSize}
            -hls_segment_type mpegts
            -hls_segment_filename %d.ts
            -f hls
            {index}
    v7:
        idleTimeout: 10s
        segmentLength: 2s
        minListLength: 8s
        maxListLength: 12s
        minInitListLength: 3s
        minPrebufferLength: 4s
        deleteThresholdLength: 4s
        ffmpegArgs: >
            -f mpegts
            -i pipe:0
            -c:v copy
            -c:a aac
            -hls_time {hlsTime}
            -hls_list_size {hlsListSize}
            -hls_segment_type fmp4
            -hls_segment_filename %d.m4s
            -f hls
            {index}

progressive:
    clientIdleTimeout: 1m
    clientMaxBufferLength: 2m
    clientResetBufferLength: 15s

logger:
    level: debug
