app:
    dataDirectory: acey

server:
    binding: 0.0.0.0:8100
    accessToken: ~
    logRequests: Y

aceApi:
    endpoint: http://127.0.0.1:6878

ttvApi:
    username: username
    password: password
    endpoint: http://api.torrent-tv.ru

stream:
    stopDelay: 3s
    sharedBufferLength: 30s
    requestTimeout: 1m
    responseTimeout: 1m

ffmpeg:
    binPath: ~
    outPath: ~
    logOutput: Y

hls:
    v3:
        idleTimeout: 15s
        requestTimeout: 1m
        segmentLength: 2s
        minListLength: 6s
        maxListLength: 10s
        minPrebufferLength: 6s
        deleteThresholdLength: 4s
        ffmpegArgs: >
            -i pipe:0
            -c copy
            -f hls
            -hls_time {hlsTime}
            -hls_list_size {hlsListSize}
            -hls_segment_type mpegts
            -hls_segment_filename %d.ts
            {index}
    v7:
        idleTimeout: 15s
        requestTimeout: 1m
        segmentLength: 2s
        minListLength: 6s
        maxListLength: 10s
        minPrebufferLength: 6s
        deleteThresholdLength: 4s
        ffmpegArgs: >
            -i pipe:0
            -c:v copy
            -c:a aac
            -f hls
            -hls_time {hlsTime}
            -hls_list_size {hlsListSize}
            -hls_segment_type fmp4
            -hls_segment_filename %d.m4s
            {index}

progressive:
    clientIdleTimeout: 1m
    clientMaxBufferLength: 2m
    clientResetBufferLength: 15s

logger:
    level: debug
